server:
  max-threads: 2000
  max-connections: 2000
spring:
  profiles:
    active: dev
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/html/
  freemarker:
        template-loader-path: classpath:/templates/
        content-type: text/html
        suffix: .ftl
        charset: utf-8
        request-context-attribute: request
        cache: false
        enabled: true
#自定义
SmsLogin:
  url: /login/mobile
  httpMethod: POST
SmsLoginParam:
  appkey: shareSdkAppkey
  mobile: mobile
  code: code
  zone: zone
WxLogin:
  url: /login/wx
  codeUrl: /login/wx/code
  antUrl: /login/**
  httpMethod: POST
WxLoginParam:
  wxToken: wxToken
  openId: openId
  appId: wx93d35060325623d3
  secret: d8884078fdbde26990199c416bb3375b
  wxUrl: https://api.weixin.qq.com/sns/userinfo?access_token=
  code: code
  wxLoginUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=
  grantType: authorization_code