spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://rm-bp1phzwe9h981t77x6o.mysql.rds.aliyuncs.com:3306/onbright_ali_new?useUnicode=true&amp;characterEncoding=utf8
    password: Iltwao!1
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-quartz

