package com.bright.apollo.request;

import java.io.Serializable;
import java.util.List;

import com.bright.apollo.common.entity.TOboxDeviceConfig;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年6月22日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OboxDTO  implements Serializable{

	/**  
	 *   
	 */
	private static final long serialVersionUID = 1L;

	
	 
	
	@JsonProperty(value="device_config")
	@Expose
	@SerializedName("device_config")
 	private List<TOboxDeviceConfig> deviceConfigs;
	
	@JsonProperty(value="group_config")
	@Expose
	@SerializedName("group_config")
 	private List<GroupDTO> groupConfigs;
	
	@JsonProperty(value="scene_config")
	@Expose
	@SerializedName("scene_config")
 	private List<SceneDTO> scenes;

	
	@Expose
	@SerializedName("obox_name")
 	@JsonProperty(value="obox_name")
	private String oboxName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_serial_id
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@JsonProperty(value="obox_serial_id")
 	@Expose
	@SerializedName("obox_serial_id")
	private String oboxSerialId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_pwd
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@JsonProperty(value="obox_pwd")
 	@Expose
 	@SerializedName("obox_pwd")
	private String oboxPwd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_version
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@JsonProperty(value="obox_version")
 	@Expose
	@SerializedName("obox_version")
	private String oboxVersion;

	 

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_status
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_status")
	@Expose
	@SerializedName("obox_status")
	private Byte oboxStatus=(byte)1;
 

 

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_addr
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_addr")
	@Expose
	@SerializedName("obox_addr")
	private String oboxAddr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_person
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_person")
	@Expose
	@SerializedName("obox_person")
	private Byte oboxPerson;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_activate
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_activate")
	@Expose
	@SerializedName("obox_activate")
	private Byte oboxActivate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_control
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_control")
	@Expose
	@SerializedName("obox_control")
	private Byte oboxControl;
	
	public List<TOboxDeviceConfig> getDeviceConfigs() {
		return deviceConfigs;
	}

	public void setDeviceConfigs(List<TOboxDeviceConfig> deviceConfigs) {
		this.deviceConfigs = deviceConfigs;
	}

	public List<SceneDTO> getScenes() {
		return scenes;
	}

	public void setScenes(List<SceneDTO> scenes) {
		this.scenes = scenes;
	}
	
	public List<GroupDTO> getGroupConfigs() {
		return groupConfigs;
	}
	
	public void setGroupConfigs(List<GroupDTO> groupConfigs) {
		this.groupConfigs = groupConfigs;
	}

	public String getOboxName() {
		return oboxName;
	}

	public void setOboxName(String oboxName) {
		this.oboxName = oboxName;
	}

	public String getOboxSerialId() {
		return oboxSerialId;
	}

	public void setOboxSerialId(String oboxSerialId) {
		this.oboxSerialId = oboxSerialId;
	}

	public String getOboxPwd() {
		return oboxPwd;
	}

	public void setOboxPwd(String oboxPwd) {
		this.oboxPwd = oboxPwd;
	}

	public String getOboxVersion() {
		return oboxVersion;
	}

	public void setOboxVersion(String oboxVersion) {
		this.oboxVersion = oboxVersion;
	}

	public Byte getOboxStatus() {
		return oboxStatus;
	}

	public void setOboxStatus(Byte oboxStatus) {
		this.oboxStatus = oboxStatus;
	}

	public String getOboxAddr() {
		return oboxAddr;
	}

	public void setOboxAddr(String oboxAddr) {
		this.oboxAddr = oboxAddr;
	}

	public Byte getOboxPerson() {
		return oboxPerson;
	}

	public void setOboxPerson(Byte oboxPerson) {
		this.oboxPerson = oboxPerson;
	}

	public Byte getOboxActivate() {
		return oboxActivate;
	}

	public void setOboxActivate(Byte oboxActivate) {
		this.oboxActivate = oboxActivate;
	}

	public Byte getOboxControl() {
		return oboxControl;
	}

	public void setOboxControl(Byte oboxControl) {
		this.oboxControl = oboxControl;
	}

	

}
