package com.bright.apollo.request;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.bright.apollo.common.entity.TScene;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年6月20日  
 *@Version:1.1.0  	
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SceneDTO  implements Serializable{

	/**  
	 *   
	 */
	private static final long serialVersionUID = 1L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.scene_number
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="scene_number")
	@Expose
	@SerializedName("scene_number")
	private Integer sceneNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.scene_name
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="scene_name")
	@Expose
	@SerializedName("scene_name")
	private String sceneName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.obox_serial_id
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="obox_serial_id")
	@Expose
	@SerializedName("obox_serial_id")
	private String oboxSerialId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.obox_scene_number
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="obox_scene_number")
	@Expose
	@SerializedName("obox_scene_number")
	private Integer oboxSceneNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.scene_status
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="scene_status")
	@Expose
	@SerializedName("scene_status")
	private Byte sceneStatus=(byte)1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.scene_type
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="scene_type")
	@Expose
	@SerializedName("scene_type")
	private String sceneType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.msg_alter
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="msg_alter")
	@Expose
	@SerializedName("msg_alter")
	private Byte msgAlter;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.last_op_time
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	private Date lastOpTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.scene_run
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="scene_run")
	@Expose
	@SerializedName("scene_run")
	private Byte sceneRun=(byte)0;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.license
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="license")
	private Integer license;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.alter_need
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="alter_need")
	private Byte alterNeed;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene.scene_group
	 *
	 * @mbg.generated Fri Jun 15 14:45:54 CST 2018
	 */
	@JsonProperty(value="scene_group")
	@Expose
	@SerializedName("scene_group")
	private String sceneGroup;
	 
	

	/**
	 * scene config
	 */
	@JsonProperty(value="actions")
	@Expose
	@SerializedName("actions")
	private List<SceneActionDTO> actions;
	@JsonProperty(value="conditions")
	@Expose
	@SerializedName("conditions")
	private List<List<SceneConditionDTO>> conditions;
	
	public List<SceneActionDTO> getActions() {
		return actions;
	}

	public void setActions(List<SceneActionDTO> actions) {
		this.actions = actions;
	}
	
	public List<List<SceneConditionDTO>> getConditions() {
		return conditions;
	}
	
	public void setConditions(List<List<SceneConditionDTO>> conditions) {
		this.conditions = conditions;
	}

	public Integer getSceneNumber() {
		return sceneNumber;
	}

	public void setSceneNumber(Integer sceneNumber) {
		this.sceneNumber = sceneNumber;
	}

	public String getSceneName() {
		return sceneName;
	}

	public void setSceneName(String sceneName) {
		this.sceneName = sceneName;
	}

	public String getOboxSerialId() {
		return oboxSerialId;
	}

	public void setOboxSerialId(String oboxSerialId) {
		this.oboxSerialId = oboxSerialId;
	}

	public Integer getOboxSceneNumber() {
		return oboxSceneNumber;
	}

	public void setOboxSceneNumber(Integer oboxSceneNumber) {
		this.oboxSceneNumber = oboxSceneNumber;
	}

	public Byte getSceneStatus() {
		return sceneStatus;
	}

	public void setSceneStatus(Byte sceneStatus) {
		this.sceneStatus = sceneStatus;
	}

	public String getSceneType() {
		return sceneType;
	}

	public void setSceneType(String sceneType) {
		this.sceneType = sceneType;
	}

	public Byte getMsgAlter() {
		return msgAlter;
	}

	public void setMsgAlter(Byte msgAlter) {
		this.msgAlter = msgAlter;
	}

	public Date getLastOpTime() {
		return lastOpTime;
	}

	public void setLastOpTime(Date lastOpTime) {
		this.lastOpTime = lastOpTime;
	}

	public Byte getSceneRun() {
		return sceneRun;
	}

	public void setSceneRun(Byte sceneRun) {
		this.sceneRun = sceneRun;
	}

	public Integer getLicense() {
		return license;
	}

	public void setLicense(Integer license) {
		this.license = license;
	}

	public Byte getAlterNeed() {
		return alterNeed;
	}

	public void setAlterNeed(Byte alterNeed) {
		this.alterNeed = alterNeed;
	}

	public String getSceneGroup() {
		return sceneGroup;
	}

	public void setSceneGroup(String sceneGroup) {
		this.sceneGroup = sceneGroup;
	}

	@Override
	public String toString() {
		return "SceneDTO [actions=" + actions + ", conditions=" + conditions
				+ "]";
	}
	public SceneDTO(TScene scene) {
		setOboxSerialId(scene.getOboxSerialId());
		setSceneNumber(scene.getSceneNumber());
		setOboxSceneNumber(scene.getOboxSceneNumber());
		setMsgAlter(scene.getMsgAlter());
		setSceneGroup(scene.getSceneGroup());
		setSceneName(scene.getSceneName());
		setSceneType(scene.getSceneType());
		setSceneStatus(scene.getSceneStatus());
	}

	/**  
	 *   
	 */
	public SceneDTO() {
		super();
	}

}