spring:
  profiles:
    active: dev
#自定义
SmsLogin:
  url: /login/mobile
  httpMethod: POST
SmsLoginParam:
  appkey: shareSdkAppkey
  mobile: mobile
  code: code
  zone: zone
WxLogin:
  url: /login/wx
  codeUrl: /login/wx/code
  antUrl: /login/**
  httpMethod: POST
WxLoginParam:
  wxToken: wxToken
  openId: openId
  appId: wx93d35060325623d3
  secret: d8884078fdbde26990199c416bb3375b
  wxUrl: https://api.weixin.qq.com/sns/userinfo?access_token=
  code: code
  wxLoginUrl: https://api.weixin.qq.com/sns/jscode2session
  grantType: authorization_code