spring:
  datasource:
    username: admin
    password: im123456
    url: jdbc:mysql://192.168.200.200:3306/bright_apollo_user?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver