package com.bright.apollo.common.entity;

import java.io.Serializable;

public class TDeviceChannelKey implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -3730518114318756492L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_channel.device_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_channel.obox_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer oboxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_channel.device_id
     *
     * @return the value of t_device_channel.device_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_channel.device_id
     *
     * @param deviceId the value for t_device_channel.device_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_channel.obox_id
     *
     * @return the value of t_device_channel.obox_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getOboxId() {
        return oboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_channel.obox_id
     *
     * @param oboxId the value for t_device_channel.obox_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setOboxId(Integer oboxId) {
        this.oboxId = oboxId;
    }
}