package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TDeviceChannelExample implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -6409456550388299054L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public TDeviceChannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Integer value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Integer value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Integer value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Integer value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Integer> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Integer> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andOboxIdIsNull() {
            addCriterion("obox_id is null");
            return (Criteria) this;
        }

        public Criteria andOboxIdIsNotNull() {
            addCriterion("obox_id is not null");
            return (Criteria) this;
        }

        public Criteria andOboxIdEqualTo(Integer value) {
            addCriterion("obox_id =", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdNotEqualTo(Integer value) {
            addCriterion("obox_id <>", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdGreaterThan(Integer value) {
            addCriterion("obox_id >", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("obox_id >=", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdLessThan(Integer value) {
            addCriterion("obox_id <", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdLessThanOrEqualTo(Integer value) {
            addCriterion("obox_id <=", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdIn(List<Integer> values) {
            addCriterion("obox_id in", values, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdNotIn(List<Integer> values) {
            addCriterion("obox_id not in", values, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdBetween(Integer value1, Integer value2) {
            addCriterion("obox_id between", value1, value2, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdNotBetween(Integer value1, Integer value2) {
            addCriterion("obox_id not between", value1, value2, "oboxId");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNull() {
            addCriterion("last_op_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNotNull() {
            addCriterion("last_op_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeEqualTo(Date value) {
            addCriterion("last_op_time =", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotEqualTo(Date value) {
            addCriterion("last_op_time <>", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThan(Date value) {
            addCriterion("last_op_time >", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_op_time >=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThan(Date value) {
            addCriterion("last_op_time <", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_op_time <=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIn(List<Date> values) {
            addCriterion("last_op_time in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotIn(List<Date> values) {
            addCriterion("last_op_time not in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeBetween(Date value1, Date value2) {
            addCriterion("last_op_time between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_op_time not between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityIsNull() {
            addCriterion("signal_intensity is null");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityIsNotNull() {
            addCriterion("signal_intensity is not null");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityEqualTo(Integer value) {
            addCriterion("signal_intensity =", value, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityNotEqualTo(Integer value) {
            addCriterion("signal_intensity <>", value, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityGreaterThan(Integer value) {
            addCriterion("signal_intensity >", value, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityGreaterThanOrEqualTo(Integer value) {
            addCriterion("signal_intensity >=", value, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityLessThan(Integer value) {
            addCriterion("signal_intensity <", value, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityLessThanOrEqualTo(Integer value) {
            addCriterion("signal_intensity <=", value, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityIn(List<Integer> values) {
            addCriterion("signal_intensity in", values, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityNotIn(List<Integer> values) {
            addCriterion("signal_intensity not in", values, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityBetween(Integer value1, Integer value2) {
            addCriterion("signal_intensity between", value1, value2, "signalIntensity");
            return (Criteria) this;
        }

        public Criteria andSignalIntensityNotBetween(Integer value1, Integer value2) {
            addCriterion("signal_intensity not between", value1, value2, "signalIntensity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_device_channel
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 02 10:21:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_device_channel
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}