package com.bright.apollo.common.entity;

import java.sql.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @Title:
 * @Description:
 * @Author:JettyLiu
 * @Since:2018年11月23日
 * @Version:1.1.0
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TDeviceLocation {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.id
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "id")
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.location
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "location")
	private Integer location;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.x_axis
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "x_axis")
	private Integer xAxis;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.y_axis
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "y_axis")
	private Integer yAxis;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.last_op_time
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "last_op_time")
	private Date lastOpTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.device_id
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "serialId")
	private String serialId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_device_location.device_type
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	@JsonProperty(value = "device_type")
	private String deviceType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_device_location.id
	 *
	 * @return the value of t_device_location.id
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_device_location.id
	 *
	 * @param id
	 *            the value for t_device_location.id
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_device_location.location
	 *
	 * @return the value of t_device_location.location
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public Integer getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_device_location.location
	 *
	 * @param location
	 *            the value for t_device_location.location
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public void setLocation(Integer location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_device_location.x_axis
	 *
	 * @return the value of t_device_location.x_axis
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public Integer getxAxis() {
		return xAxis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_device_location.x_axis
	 *
	 * @param xAxis
	 *            the value for t_device_location.x_axis
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public void setxAxis(Integer xAxis) {
		this.xAxis = xAxis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_device_location.y_axis
	 *
	 * @return the value of t_device_location.y_axis
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public Integer getyAxis() {
		return yAxis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_device_location.y_axis
	 *
	 * @param yAxis
	 *            the value for t_device_location.y_axis
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public void setyAxis(Integer yAxis) {
		this.yAxis = yAxis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_device_location.last_op_time
	 *
	 * @return the value of t_device_location.last_op_time
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public Date getLastOpTime() {
		return lastOpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_device_location.last_op_time
	 *
	 * @param lastOpTime
	 *            the value for t_device_location.last_op_time
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public void setLastOpTime(Date lastOpTime) {
		this.lastOpTime = lastOpTime;
	}

	public String getSerialId() {
		return serialId;
	}

	public void setSerialId(String serialId) {
		this.serialId = serialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_device_location.device_type
	 *
	 * @return the value of t_device_location.device_type
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public String getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_device_location.device_type
	 *
	 * @param deviceType
	 *            the value for t_device_location.device_type
	 *
	 * @mbg.generated Fri Nov 23 15:52:07 CST 2018
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType == null ? null : deviceType.trim();
	}

}
