package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年8月28日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TDeviceStatus implements Serializable{

    /**  
	 *   
	 */
	private static final long serialVersionUID = 7219015382957669314L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.id
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.device_serial_id
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    private String deviceSerialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.device_state
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    private String deviceState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_status.last_op_time
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.id
     *
     * @return the value of t_device_status.id
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.id
     *
     * @param id the value for t_device_status.id
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.device_serial_id
     *
     * @return the value of t_device_status.device_serial_id
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public String getDeviceSerialId() {
        return deviceSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.device_serial_id
     *
     * @param deviceSerialId the value for t_device_status.device_serial_id
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public void setDeviceSerialId(String deviceSerialId) {
        this.deviceSerialId = deviceSerialId == null ? null : deviceSerialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.device_state
     *
     * @return the value of t_device_status.device_state
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public String getDeviceState() {
        return deviceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.device_state
     *
     * @param deviceState the value for t_device_status.device_state
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public void setDeviceState(String deviceState) {
        this.deviceState = deviceState == null ? null : deviceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_status.last_op_time
     *
     * @return the value of t_device_status.last_op_time
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_status.last_op_time
     *
     * @param lastOpTime the value for t_device_status.last_op_time
     *
     * @mbg.generated Tue Aug 28 15:23:45 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

}
