package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

public class TDeviceChannel extends TDeviceChannelKey implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 4850753712022393627L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_channel.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_channel.signal_intensity
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer signalIntensity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_channel.last_op_time
     *
     * @return the value of t_device_channel.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_channel.last_op_time
     *
     * @param lastOpTime the value for t_device_channel.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_channel.signal_intensity
     *
     * @return the value of t_device_channel.signal_intensity
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getSignalIntensity() {
        return signalIntensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_channel.signal_intensity
     *
     * @param signalIntensity the value for t_device_channel.signal_intensity
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setSignalIntensity(Integer signalIntensity) {
        this.signalIntensity = signalIntensity;
    }
}