package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.zz.common.util.StringUtils;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TException implements Serializable{
 
	/**  
	 *   
	 */
	private static final long serialVersionUID = 3192985280013871969L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.last_op_time
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.type
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.child_type
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private Integer childType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.relevancy_id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private Integer relevancyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.state
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.device_serial_id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private String deviceSerialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exception.device_name
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    private String deviceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.id
     *
     * @return the value of t_exception.id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.id
     *
     * @param id the value for t_exception.id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.last_op_time
     *
     * @return the value of t_exception.last_op_time
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.last_op_time
     *
     * @param lastOpTime the value for t_exception.last_op_time
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.type
     *
     * @return the value of t_exception.type
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.type
     *
     * @param type the value for t_exception.type
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.child_type
     *
     * @return the value of t_exception.child_type
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public Integer getChildType() {
        return childType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.child_type
     *
     * @param childType the value for t_exception.child_type
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setChildType(Integer childType) {
        this.childType = childType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.relevancy_id
     *
     * @return the value of t_exception.relevancy_id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public Integer getRelevancyId() {
        return relevancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.relevancy_id
     *
     * @param relevancyId the value for t_exception.relevancy_id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setRelevancyId(Integer relevancyId) {
        this.relevancyId = relevancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.state
     *
     * @return the value of t_exception.state
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.state
     *
     * @param state the value for t_exception.state
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.device_serial_id
     *
     * @return the value of t_exception.device_serial_id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public String getDeviceSerialId() {
        return deviceSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.device_serial_id
     *
     * @param deviceSerialId the value for t_exception.device_serial_id
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setDeviceSerialId(String deviceSerialId) {
        this.deviceSerialId = deviceSerialId == null ? null : deviceSerialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exception.device_name
     *
     * @return the value of t_exception.device_name
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exception.device_name
     *
     * @param deviceName the value for t_exception.device_name
     *
     * @mbg.generated Fri Oct 19 11:47:31 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }
    public TException(Integer type, Integer childType, String state,
			Integer relevancyId,String deviceSerialId,String deviceName) {
		super();
		this.type = type;
		this.childType = childType;
		if(!StringUtils.isEmpty(state))
			this.state = state;
		this.relevancyId = relevancyId;
		if(!StringUtils.isEmpty(deviceSerialId))
			this.deviceSerialId=deviceSerialId;
		if(!StringUtils.isEmpty(deviceName))
			this.deviceName=deviceName;
	}

	public TException() {
		super();
	}
}