package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TGroupDevice implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 183713330466528547L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_device.group_id
     *
     * @mbg.generated Tue Oct 30 15:23:22 CST 2018
     */
    private Integer groupId;

     
    private String deviceSerialId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_device.last_op_time
     *
     * @mbg.generated Tue Oct 30 15:23:22 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_device.group_id
     *
     * @return the value of t_group_device.group_id
     *
     * @mbg.generated Tue Oct 30 15:23:22 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_device.group_id
     *
     * @param groupId the value for t_group_device.group_id
     *
     * @mbg.generated Tue Oct 30 15:23:22 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_device.last_op_time
     *
     * @return the value of t_group_device.last_op_time
     *
     * @mbg.generated Tue Oct 30 15:23:22 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_device.last_op_time
     *
     * @param lastOpTime the value for t_group_device.last_op_time
     *
     * @mbg.generated Tue Oct 30 15:23:22 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

	public String getDeviceSerialId() {
		return deviceSerialId;
	}

	public void setDeviceSerialId(String deviceSerialId) {
		this.deviceSerialId = deviceSerialId;
	}
    
}