package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIntelligentFingerUser implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -503683753321451971L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String serialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.mobile
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.exist_force
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    @JsonProperty(value="exist")
    private Integer existForce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.pin
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String pin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.identity
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_user.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.id
     *
     * @return the value of t_intelligent_finger_user.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.id
     *
     * @param id the value for t_intelligent_finger_user.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.serialId
     *
     * @return the value of t_intelligent_finger_user.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.serialId
     *
     * @param serialid the value for t_intelligent_finger_user.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.nick_name
     *
     * @return the value of t_intelligent_finger_user.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.nick_name
     *
     * @param nickName the value for t_intelligent_finger_user.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.mobile
     *
     * @return the value of t_intelligent_finger_user.mobile
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.mobile
     *
     * @param mobile the value for t_intelligent_finger_user.mobile
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.exist_force
     *
     * @return the value of t_intelligent_finger_user.exist_force
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getExistForce() {
        return existForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.exist_force
     *
     * @param existForce the value for t_intelligent_finger_user.exist_force
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setExistForce(Integer existForce) {
        this.existForce = existForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.pin
     *
     * @return the value of t_intelligent_finger_user.pin
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.pin
     *
     * @param pin the value for t_intelligent_finger_user.pin
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.identity
     *
     * @return the value of t_intelligent_finger_user.identity
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.identity
     *
     * @param identity the value for t_intelligent_finger_user.identity
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setIdentity(Integer identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_user.last_op_time
     *
     * @return the value of t_intelligent_finger_user.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_user.last_op_time
     *
     * @param lastOpTime the value for t_intelligent_finger_user.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }
}