package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIntelligentFingerRecord implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -4331908662522678278L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_record.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_record.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String serialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_record.finger_user_id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer fingerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_record.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_record.operation
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_record.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_record.id
     *
     * @return the value of t_intelligent_finger_record.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_record.id
     *
     * @param id the value for t_intelligent_finger_record.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_record.serialId
     *
     * @return the value of t_intelligent_finger_record.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_record.serialId
     *
     * @param serialid the value for t_intelligent_finger_record.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_record.finger_user_id
     *
     * @return the value of t_intelligent_finger_record.finger_user_id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getFingerUserId() {
        return fingerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_record.finger_user_id
     *
     * @param fingerUserId the value for t_intelligent_finger_record.finger_user_id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setFingerUserId(Integer fingerUserId) {
        this.fingerUserId = fingerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_record.nick_name
     *
     * @return the value of t_intelligent_finger_record.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_record.nick_name
     *
     * @param nickName the value for t_intelligent_finger_record.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_record.operation
     *
     * @return the value of t_intelligent_finger_record.operation
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_record.operation
     *
     * @param operation the value for t_intelligent_finger_record.operation
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_record.last_op_time
     *
     * @return the value of t_intelligent_finger_record.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_record.last_op_time
     *
     * @param lastOpTime the value for t_intelligent_finger_record.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }
}