package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TIntelligentFingerRemoteUser implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 741143542681393479L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.user_serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    @JsonProperty(value="userSerialId")
    private Integer userSerialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.mobile
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    @JsonProperty(value="serialId")
    private String serialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.start_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.end_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.times
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.use_times
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Integer useTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.pwd
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.isEnd
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    @JsonProperty(value="isEnd")
    private Integer isend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.isMax
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    @JsonProperty(value="isMax")
    private Integer ismax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligent_finger_remote_user.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    private Date lastOpTime;

   

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.id
     *
     * @return the value of t_intelligent_finger_remote_user.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.id
     *
     * @param id the value for t_intelligent_finger_remote_user.id
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.user_serialId
     *
     * @return the value of t_intelligent_finger_remote_user.user_serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getUserSerialid() {
        return userSerialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.user_serialId
     *
     * @param userSerialid the value for t_intelligent_finger_remote_user.user_serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setUserSerialid(Integer userSerialid) {
        this.userSerialid = userSerialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.mobile
     *
     * @return the value of t_intelligent_finger_remote_user.mobile
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.mobile
     *
     * @param mobile the value for t_intelligent_finger_remote_user.mobile
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.serialId
     *
     * @return the value of t_intelligent_finger_remote_user.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.serialId
     *
     * @param serialid the value for t_intelligent_finger_remote_user.serialId
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.nick_name
     *
     * @return the value of t_intelligent_finger_remote_user.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.nick_name
     *
     * @param nickName the value for t_intelligent_finger_remote_user.nick_name
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.start_time
     *
     * @return the value of t_intelligent_finger_remote_user.start_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.start_time
     *
     * @param startTime the value for t_intelligent_finger_remote_user.start_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.end_time
     *
     * @return the value of t_intelligent_finger_remote_user.end_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.end_time
     *
     * @param endTime the value for t_intelligent_finger_remote_user.end_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.times
     *
     * @return the value of t_intelligent_finger_remote_user.times
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.times
     *
     * @param times the value for t_intelligent_finger_remote_user.times
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.use_times
     *
     * @return the value of t_intelligent_finger_remote_user.use_times
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getUseTimes() {
        return useTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.use_times
     *
     * @param useTimes the value for t_intelligent_finger_remote_user.use_times
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setUseTimes(Integer useTimes) {
        this.useTimes = useTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.pwd
     *
     * @return the value of t_intelligent_finger_remote_user.pwd
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.pwd
     *
     * @param pwd the value for t_intelligent_finger_remote_user.pwd
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.isEnd
     *
     * @return the value of t_intelligent_finger_remote_user.isEnd
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.isEnd
     *
     * @param isend the value for t_intelligent_finger_remote_user.isEnd
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.isMax
     *
     * @return the value of t_intelligent_finger_remote_user.isMax
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Integer getIsmax() {
        return ismax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.isMax
     *
     * @param ismax the value for t_intelligent_finger_remote_user.isMax
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setIsmax(Integer ismax) {
        this.ismax = ismax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligent_finger_remote_user.last_op_time
     *
     * @return the value of t_intelligent_finger_remote_user.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligent_finger_remote_user.last_op_time
     *
     * @param lastOpTime the value for t_intelligent_finger_remote_user.last_op_time
     *
     * @mbg.generated Mon Aug 06 10:56:24 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

	/**  
	 * @param userSerialid
	 * @param mobile
	 * @param serialid
	 * @param nickName
	 * @param startTime
	 * @param endTime
	 * @param times
	 * @param pwd
	 * @param ismax  
	 */
	public TIntelligentFingerRemoteUser(Integer userSerialid, String mobile, String serialid, String nickName,
			String startTime, String endTime, Integer times, String pwd, Integer ismax) {
		super();
		this.userSerialid = userSerialid;
		this.mobile = mobile;
		this.serialid = serialid;
		this.nickName = nickName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.times = times;
		this.pwd = pwd;
		this.ismax = ismax;
	}

	/**  
	 * @param userSerialid
	 * @param mobile
	 * @param serialid
	 * @param nickName
	 * @param startTime
	 * @param endTime
	 * @param times
	 * @param pwd  
	 */
	public TIntelligentFingerRemoteUser(Integer userSerialid, String mobile, String serialid, String nickName,
			String startTime, String endTime, Integer times, String pwd) {
		super();
		this.userSerialid = userSerialid;
		this.mobile = mobile;
		this.serialid = serialid;
		this.nickName = nickName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.times = times;
		this.pwd = pwd;
	}

	/**  
	 *   
	 */
	public TIntelligentFingerRemoteUser() {
		super();
	}
    
	
}