package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.util.StringUtils;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年11月23日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TLocation implements Serializable{

    /**  
	 *   
	 */
	private static final long serialVersionUID = -8405334109632822430L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.id
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
	@JsonProperty(value = "location")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.building
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
	@JsonProperty(value = "building")
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.room
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
	@JsonProperty(value = "room")
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.download_url
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
	@JsonProperty(value = "download_url")
	private String downloadUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.last_op_time
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.license
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    @JsonProperty(value = "license")
    private Integer license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.thum_url
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    @JsonProperty(value = "thum_url")
    private String thumUrl;

    @JsonProperty(value = "status")
    private Integer status;
    @JsonProperty(value = "userName")
    private String userName;
    @JsonProperty(value = "type")
    private String type;
    @JsonProperty(value = "layer")
    private String layer;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.id
     *
     * @return the value of t_location.id
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.id
     *
     * @param id the value for t_location.id
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.building
     *
     * @return the value of t_location.building
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.building
     *
     * @param building the value for t_location.building
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setBuilding(String building) {
        this.building = building == null ? null : building.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.room
     *
     * @return the value of t_location.room
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.room
     *
     * @param room the value for t_location.room
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.download_url
     *
     * @return the value of t_location.download_url
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.download_url
     *
     * @param downloadUrl the value for t_location.download_url
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.last_op_time
     *
     * @return the value of t_location.last_op_time
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.last_op_time
     *
     * @param lastOpTime the value for t_location.last_op_time
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.license
     *
     * @return the value of t_location.license
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public Integer getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.license
     *
     * @param license the value for t_location.license
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setLicense(Integer license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.thum_url
     *
     * @return the value of t_location.thum_url
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public String getThumUrl() {
        return thumUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.thum_url
     *
     * @param thumUrl the value for t_location.thum_url
     *
     * @mbg.generated Fri Nov 23 15:02:34 CST 2018
     */
    public void setThumUrl(String thumUrl) {
        this.thumUrl = thumUrl == null ? null : thumUrl.trim();
    }

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLayer() {
		return layer;
	}

	public void setLayer(String layer) {
		this.layer = layer;
	}

	/**  
	 *   
	 */
	public TLocation() {
		super();
	}

	/**  
	 * @param building
	 * @param room
	 * @param type
	 * @param layer  
	 */
	public TLocation(String building, String room, String type, String layer) {
		super();
		if(!StringUtils.isEmpty(building))
			this.building = building;
		if(!StringUtils.isEmpty(type))
			this.type = type;
		if(!StringUtils.isEmpty(layer))
			this.layer = layer;
		this.room = room;
	}

}
