package com.bright.apollo.common.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TLocationScene {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location_scene.location_id
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location_scene.scene_number
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    private Integer sceneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location_scene.last_op_time
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location_scene.location_id
     *
     * @return the value of t_location_scene.location_id
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location_scene.location_id
     *
     * @param locationId the value for t_location_scene.location_id
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location_scene.scene_number
     *
     * @return the value of t_location_scene.scene_number
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    public Integer getSceneNumber() {
        return sceneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location_scene.scene_number
     *
     * @param sceneNumber the value for t_location_scene.scene_number
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    public void setSceneNumber(Integer sceneNumber) {
        this.sceneNumber = sceneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location_scene.last_op_time
     *
     * @return the value of t_location_scene.last_op_time
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location_scene.last_op_time
     *
     * @param lastOpTime the value for t_location_scene.last_op_time
     *
     * @mbg.generated Tue Nov 27 17:28:44 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }
}