package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TMsg implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 3989847486672917348L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.last_op_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.user_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.content
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.relevancy_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer relevancyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.state
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.send_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Long sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.url
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.id
     *
     * @return the value of t_msg.id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.id
     *
     * @param id the value for t_msg.id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.last_op_time
     *
     * @return the value of t_msg.last_op_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.last_op_time
     *
     * @param lastOpTime the value for t_msg.last_op_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.type
     *
     * @return the value of t_msg.type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.type
     *
     * @param type the value for t_msg.type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.user_id
     *
     * @return the value of t_msg.user_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.user_id
     *
     * @param userId the value for t_msg.user_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.content
     *
     * @return the value of t_msg.content
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.content
     *
     * @param content the value for t_msg.content
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.relevancy_id
     *
     * @return the value of t_msg.relevancy_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getRelevancyId() {
        return relevancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.relevancy_id
     *
     * @param relevancyId the value for t_msg.relevancy_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setRelevancyId(Integer relevancyId) {
        this.relevancyId = relevancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.state
     *
     * @return the value of t_msg.state
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.state
     *
     * @param state the value for t_msg.state
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.send_time
     *
     * @return the value of t_msg.send_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Long getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.send_time
     *
     * @param sendTime the value for t_msg.send_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.url
     *
     * @return the value of t_msg.url
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.url
     *
     * @param url the value for t_msg.url
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
    public TMsg(Integer type, Integer userId, String content,
			Integer relevancyId,Long sendTime ) {
		super();
		this.type = type;
		this.userId = userId;
		this.content = content;
		this.relevancyId = relevancyId;
		this.sendTime=sendTime;
	}
	public TMsg(Integer type, Integer userId, String content,
			Integer relevancyId,Long sendTime,String url ) {
		super();
		this.type = type;
		this.userId = userId;
		this.content = content;
		this.relevancyId = relevancyId;
		this.sendTime=sendTime;
		this.url=url;
	}
	public TMsg() {
		super();
	}

}