package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年6月28日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TNvr implements Serializable {

	/**  
	 *   
	 */
	private static final long serialVersionUID = 2286690855314387439L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.id
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.ip
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.port
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.user
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.pw
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private String pw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.license
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private Integer license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nvr.last_op_time
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.id
     *
     * @return the value of t_nvr.id
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.id
     *
     * @param id the value for t_nvr.id
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.ip
     *
     * @return the value of t_nvr.ip
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.ip
     *
     * @param ip the value for t_nvr.ip
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.port
     *
     * @return the value of t_nvr.port
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.port
     *
     * @param port the value for t_nvr.port
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.user
     *
     * @return the value of t_nvr.user
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.user
     *
     * @param user the value for t_nvr.user
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.pw
     *
     * @return the value of t_nvr.pw
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.pw
     *
     * @param pw the value for t_nvr.pw
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setPw(String pw) {
        this.pw = pw == null ? null : pw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.license
     *
     * @return the value of t_nvr.license
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public Integer getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.license
     *
     * @param license the value for t_nvr.license
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setLicense(Integer license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nvr.last_op_time
     *
     * @return the value of t_nvr.last_op_time
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nvr.last_op_time
     *
     * @param lastOpTime the value for t_nvr.last_op_time
     *
     * @mbg.generated Thu Jun 28 15:15:01 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

}
