package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(value={"id"})
public class TObox implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 2199951616230400490L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.obox_name
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private String oboxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.obox_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private String oboxSerialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.obox_version
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private String oboxVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.obox_status
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer oboxStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_obox.obox_ip
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private String oboxIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.id
     *
     * @return the value of t_obox.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.id
     *
     * @param id the value for t_obox.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.obox_name
     *
     * @return the value of t_obox.obox_name
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOboxName() {
        return oboxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.obox_name
     *
     * @param oboxName the value for t_obox.obox_name
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOboxName(String oboxName) {
        this.oboxName = oboxName == null ? null : oboxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.obox_serial_id
     *
     * @return the value of t_obox.obox_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOboxSerialId() {
        return oboxSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.obox_serial_id
     *
     * @param oboxSerialId the value for t_obox.obox_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOboxSerialId(String oboxSerialId) {
        this.oboxSerialId = oboxSerialId == null ? null : oboxSerialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.obox_version
     *
     * @return the value of t_obox.obox_version
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOboxVersion() {
        return oboxVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.obox_version
     *
     * @param oboxVersion the value for t_obox.obox_version
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOboxVersion(String oboxVersion) {
        this.oboxVersion = oboxVersion == null ? null : oboxVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.last_op_time
     *
     * @return the value of t_obox.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.last_op_time
     *
     * @param lastOpTime the value for t_obox.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.obox_status
     *
     * @return the value of t_obox.obox_status
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getOboxStatus() {
        return oboxStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.obox_status
     *
     * @param oboxStatus the value for t_obox.obox_status
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOboxStatus(Integer oboxStatus) {
        this.oboxStatus = oboxStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_obox.obox_ip
     *
     * @return the value of t_obox.obox_ip
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOboxIp() {
        return oboxIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_obox.obox_ip
     *
     * @param oboxIp the value for t_obox.obox_ip
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOboxIp(String oboxIp) {
        this.oboxIp = oboxIp == null ? null : oboxIp.trim();
    }

	/**  
	 * @param id
	 * @param oboxName
	 * @param oboxSerialId
	 * @param oboxVersion
	 * @param lastOpTime
	 * @param oboxStatus
	 * @param oboxIp  
	 */
	public TObox(Integer id, String oboxName, String oboxSerialId, String oboxVersion, Date lastOpTime,
			Integer oboxStatus, String oboxIp) {
		super();
		this.id = id;
		this.oboxName = oboxName;
		this.oboxSerialId = oboxSerialId;
		this.oboxVersion = oboxVersion;
		this.lastOpTime = lastOpTime;
		this.oboxStatus = oboxStatus;
		this.oboxIp = oboxIp;
	}

	/**  
	 * @param id  
	 */
	public TObox(Integer id) {
		super();
		this.id = id;
	}

	/**  
	 *   
	 */
	public TObox() {
		super();
	}
    
}