package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TOboxDeviceConfigExample implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -6681710338154956579L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public TOboxDeviceConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOboxIdIsNull() {
            addCriterion("obox_id is null");
            return (Criteria) this;
        }

        public Criteria andOboxIdIsNotNull() {
            addCriterion("obox_id is not null");
            return (Criteria) this;
        }

        public Criteria andOboxIdEqualTo(Integer value) {
            addCriterion("obox_id =", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdNotEqualTo(Integer value) {
            addCriterion("obox_id <>", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdGreaterThan(Integer value) {
            addCriterion("obox_id >", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("obox_id >=", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdLessThan(Integer value) {
            addCriterion("obox_id <", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdLessThanOrEqualTo(Integer value) {
            addCriterion("obox_id <=", value, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdIn(List<Integer> values) {
            addCriterion("obox_id in", values, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdNotIn(List<Integer> values) {
            addCriterion("obox_id not in", values, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdBetween(Integer value1, Integer value2) {
            addCriterion("obox_id between", value1, value2, "oboxId");
            return (Criteria) this;
        }

        public Criteria andOboxIdNotBetween(Integer value1, Integer value2) {
            addCriterion("obox_id not between", value1, value2, "oboxId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceStateIsNull() {
            addCriterion("device_state is null");
            return (Criteria) this;
        }

        public Criteria andDeviceStateIsNotNull() {
            addCriterion("device_state is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceStateEqualTo(String value) {
            addCriterion("device_state =", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateNotEqualTo(String value) {
            addCriterion("device_state <>", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateGreaterThan(String value) {
            addCriterion("device_state >", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateGreaterThanOrEqualTo(String value) {
            addCriterion("device_state >=", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateLessThan(String value) {
            addCriterion("device_state <", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateLessThanOrEqualTo(String value) {
            addCriterion("device_state <=", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateLike(String value) {
            addCriterion("device_state like", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateNotLike(String value) {
            addCriterion("device_state not like", value, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateIn(List<String> values) {
            addCriterion("device_state in", values, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateNotIn(List<String> values) {
            addCriterion("device_state not in", values, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateBetween(String value1, String value2) {
            addCriterion("device_state between", value1, value2, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceStateNotBetween(String value1, String value2) {
            addCriterion("device_state not between", value1, value2, "deviceState");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("device_type is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("device_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("device_type =", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("device_type <>", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("device_type >", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("device_type >=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("device_type <", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("device_type <=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("device_type like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("device_type not like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIn(List<String> values) {
            addCriterion("device_type in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotIn(List<String> values) {
            addCriterion("device_type not in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("device_type between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("device_type not between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeIsNull() {
            addCriterion("device_child_type is null");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeIsNotNull() {
            addCriterion("device_child_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeEqualTo(String value) {
            addCriterion("device_child_type =", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeNotEqualTo(String value) {
            addCriterion("device_child_type <>", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeGreaterThan(String value) {
            addCriterion("device_child_type >", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeGreaterThanOrEqualTo(String value) {
            addCriterion("device_child_type >=", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeLessThan(String value) {
            addCriterion("device_child_type <", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeLessThanOrEqualTo(String value) {
            addCriterion("device_child_type <=", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeLike(String value) {
            addCriterion("device_child_type like", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeNotLike(String value) {
            addCriterion("device_child_type not like", value, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeIn(List<String> values) {
            addCriterion("device_child_type in", values, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeNotIn(List<String> values) {
            addCriterion("device_child_type not in", values, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeBetween(String value1, String value2) {
            addCriterion("device_child_type between", value1, value2, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceChildTypeNotBetween(String value1, String value2) {
            addCriterion("device_child_type not between", value1, value2, "deviceChildType");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionIsNull() {
            addCriterion("device_version is null");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionIsNotNull() {
            addCriterion("device_version is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionEqualTo(String value) {
            addCriterion("device_version =", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionNotEqualTo(String value) {
            addCriterion("device_version <>", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionGreaterThan(String value) {
            addCriterion("device_version >", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionGreaterThanOrEqualTo(String value) {
            addCriterion("device_version >=", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionLessThan(String value) {
            addCriterion("device_version <", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionLessThanOrEqualTo(String value) {
            addCriterion("device_version <=", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionLike(String value) {
            addCriterion("device_version like", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionNotLike(String value) {
            addCriterion("device_version not like", value, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionIn(List<String> values) {
            addCriterion("device_version in", values, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionNotIn(List<String> values) {
            addCriterion("device_version not in", values, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionBetween(String value1, String value2) {
            addCriterion("device_version between", value1, value2, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceVersionNotBetween(String value1, String value2) {
            addCriterion("device_version not between", value1, value2, "deviceVersion");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNull() {
            addCriterion("last_op_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNotNull() {
            addCriterion("last_op_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeEqualTo(Date value) {
            addCriterion("last_op_time =", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotEqualTo(Date value) {
            addCriterion("last_op_time <>", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThan(Date value) {
            addCriterion("last_op_time >", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_op_time >=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThan(Date value) {
            addCriterion("last_op_time <", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_op_time <=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIn(List<Date> values) {
            addCriterion("last_op_time in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotIn(List<Date> values) {
            addCriterion("last_op_time not in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeBetween(Date value1, Date value2) {
            addCriterion("last_op_time between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_op_time not between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdIsNull() {
            addCriterion("device_serial_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdIsNotNull() {
            addCriterion("device_serial_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdEqualTo(String value) {
            addCriterion("device_serial_id =", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotEqualTo(String value) {
            addCriterion("device_serial_id <>", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdGreaterThan(String value) {
            addCriterion("device_serial_id >", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdGreaterThanOrEqualTo(String value) {
            addCriterion("device_serial_id >=", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdLessThan(String value) {
            addCriterion("device_serial_id <", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdLessThanOrEqualTo(String value) {
            addCriterion("device_serial_id <=", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdLike(String value) {
            addCriterion("device_serial_id like", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotLike(String value) {
            addCriterion("device_serial_id not like", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdIn(List<String> values) {
            addCriterion("device_serial_id in", values, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotIn(List<String> values) {
            addCriterion("device_serial_id not in", values, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdBetween(String value1, String value2) {
            addCriterion("device_serial_id between", value1, value2, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotBetween(String value1, String value2) {
            addCriterion("device_serial_id not between", value1, value2, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrIsNull() {
            addCriterion("device_rf_addr is null");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrIsNotNull() {
            addCriterion("device_rf_addr is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrEqualTo(String value) {
            addCriterion("device_rf_addr =", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrNotEqualTo(String value) {
            addCriterion("device_rf_addr <>", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrGreaterThan(String value) {
            addCriterion("device_rf_addr >", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrGreaterThanOrEqualTo(String value) {
            addCriterion("device_rf_addr >=", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrLessThan(String value) {
            addCriterion("device_rf_addr <", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrLessThanOrEqualTo(String value) {
            addCriterion("device_rf_addr <=", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrLike(String value) {
            addCriterion("device_rf_addr like", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrNotLike(String value) {
            addCriterion("device_rf_addr not like", value, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrIn(List<String> values) {
            addCriterion("device_rf_addr in", values, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrNotIn(List<String> values) {
            addCriterion("device_rf_addr not in", values, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrBetween(String value1, String value2) {
            addCriterion("device_rf_addr between", value1, value2, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andDeviceRfAddrNotBetween(String value1, String value2) {
            addCriterion("device_rf_addr not between", value1, value2, "deviceRfAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrIsNull() {
            addCriterion("group_addr is null");
            return (Criteria) this;
        }

        public Criteria andGroupAddrIsNotNull() {
            addCriterion("group_addr is not null");
            return (Criteria) this;
        }

        public Criteria andGroupAddrEqualTo(String value) {
            addCriterion("group_addr =", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrNotEqualTo(String value) {
            addCriterion("group_addr <>", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrGreaterThan(String value) {
            addCriterion("group_addr >", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrGreaterThanOrEqualTo(String value) {
            addCriterion("group_addr >=", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrLessThan(String value) {
            addCriterion("group_addr <", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrLessThanOrEqualTo(String value) {
            addCriterion("group_addr <=", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrLike(String value) {
            addCriterion("group_addr like", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrNotLike(String value) {
            addCriterion("group_addr not like", value, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrIn(List<String> values) {
            addCriterion("group_addr in", values, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrNotIn(List<String> values) {
            addCriterion("group_addr not in", values, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrBetween(String value1, String value2) {
            addCriterion("group_addr between", value1, value2, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andGroupAddrNotBetween(String value1, String value2) {
            addCriterion("group_addr not between", value1, value2, "groupAddr");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdIsNull() {
            addCriterion("obox_serial_id is null");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdIsNotNull() {
            addCriterion("obox_serial_id is not null");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdEqualTo(String value) {
            addCriterion("obox_serial_id =", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotEqualTo(String value) {
            addCriterion("obox_serial_id <>", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdGreaterThan(String value) {
            addCriterion("obox_serial_id >", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdGreaterThanOrEqualTo(String value) {
            addCriterion("obox_serial_id >=", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdLessThan(String value) {
            addCriterion("obox_serial_id <", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdLessThanOrEqualTo(String value) {
            addCriterion("obox_serial_id <=", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdLike(String value) {
            addCriterion("obox_serial_id like", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotLike(String value) {
            addCriterion("obox_serial_id not like", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdIn(List<String> values) {
            addCriterion("obox_serial_id in", values, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotIn(List<String> values) {
            addCriterion("obox_serial_id not in", values, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdBetween(String value1, String value2) {
            addCriterion("obox_serial_id between", value1, value2, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotBetween(String value1, String value2) {
            addCriterion("obox_serial_id not between", value1, value2, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOnlineIsNull() {
            addCriterion("online is null");
            return (Criteria) this;
        }

        public Criteria andOnlineIsNotNull() {
            addCriterion("online is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineEqualTo(Integer value) {
            addCriterion("online =", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineNotEqualTo(Integer value) {
            addCriterion("online <>", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineGreaterThan(Integer value) {
            addCriterion("online >", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineGreaterThanOrEqualTo(Integer value) {
            addCriterion("online >=", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineLessThan(Integer value) {
            addCriterion("online <", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineLessThanOrEqualTo(Integer value) {
            addCriterion("online <=", value, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineIn(List<Integer> values) {
            addCriterion("online in", values, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineNotIn(List<Integer> values) {
            addCriterion("online not in", values, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineBetween(Integer value1, Integer value2) {
            addCriterion("online between", value1, value2, "online");
            return (Criteria) this;
        }

        public Criteria andOnlineNotBetween(Integer value1, Integer value2) {
            addCriterion("online not between", value1, value2, "online");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_obox_device_config
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 14 16:07:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_obox_device_config
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}