package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(value = { "lastOpTime","oboxIp" })
public class TObox implements Serializable {
	/**  
	 *   
	 */
	private static final long serialVersionUID = 1L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_id
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	 
 	@JsonProperty(value="id")
 	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_name
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@Expose
	@SerializedName("obox_name")
 	@JsonProperty(value="obox_name")
	private String oboxName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_serial_id
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@JsonProperty(value="obox_serial_id")
 	@Expose
	@SerializedName("obox_serial_id")
	private String oboxSerialId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_pwd
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@JsonProperty(value="obox_pwd")
 	@Expose
 	@SerializedName("obox_pwd")
	private String oboxPwd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_version
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
 	@JsonProperty(value="obox_version")
 	@Expose
	@SerializedName("obox_version")
	private String oboxVersion;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.last_op_time
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	private Date lastOpTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_status
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_status")
	@Expose
	@SerializedName("obox_status")
	private Byte oboxStatus=(byte)1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.license
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	private Integer license;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_ip
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_ip")
	private String oboxIp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_addr
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_addr")
	@Expose
	@SerializedName("obox_addr")
	private String oboxAddr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_person
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_person")
	@Expose
	@SerializedName("obox_person")
	private Byte oboxPerson;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_activate
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_activate")
	@Expose
	@SerializedName("obox_activate")
	private Byte oboxActivate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_obox.obox_control
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	@JsonProperty(value="obox_control")
	@Expose
	@SerializedName("obox_control")
	private Byte oboxControl;

	  

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_name
	 *
	 * @return the value of t_obox.obox_name
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public String getOboxName() {
		return oboxName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_name
	 *
	 * @param oboxName
	 *            the value for t_obox.obox_name
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxName(String oboxName) {
		this.oboxName = oboxName == null ? null : oboxName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_serial_id
	 *
	 * @return the value of t_obox.obox_serial_id
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public String getOboxSerialId() {
		return oboxSerialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_serial_id
	 *
	 * @param oboxSerialId
	 *            the value for t_obox.obox_serial_id
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxSerialId(String oboxSerialId) {
		this.oboxSerialId = oboxSerialId == null ? null : oboxSerialId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_pwd
	 *
	 * @return the value of t_obox.obox_pwd
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public String getOboxPwd() {
		return oboxPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_pwd
	 *
	 * @param oboxPwd
	 *            the value for t_obox.obox_pwd
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxPwd(String oboxPwd) {
		this.oboxPwd = oboxPwd == null ? null : oboxPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_version
	 *
	 * @return the value of t_obox.obox_version
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public String getOboxVersion() {
		return oboxVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_version
	 *
	 * @param oboxVersion
	 *            the value for t_obox.obox_version
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxVersion(String oboxVersion) {
		this.oboxVersion = oboxVersion == null ? null : oboxVersion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.last_op_time
	 *
	 * @return the value of t_obox.last_op_time
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public Date getLastOpTime() {
		return lastOpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.last_op_time
	 *
	 * @param lastOpTime
	 *            the value for t_obox.last_op_time
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setLastOpTime(Date lastOpTime) {
		this.lastOpTime = lastOpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_status
	 *
	 * @return the value of t_obox.obox_status
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public Byte getOboxStatus() {
		return oboxStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_status
	 *
	 * @param oboxStatus
	 *            the value for t_obox.obox_status
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxStatus(Byte oboxStatus) {
		this.oboxStatus = oboxStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.license
	 *
	 * @return the value of t_obox.license
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public Integer getLicense() {
		return license;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.license
	 *
	 * @param license
	 *            the value for t_obox.license
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setLicense(Integer license) {
		this.license = license;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_ip
	 *
	 * @return the value of t_obox.obox_ip
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public String getOboxIp() {
		return oboxIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_ip
	 *
	 * @param oboxIp
	 *            the value for t_obox.obox_ip
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxIp(String oboxIp) {
		this.oboxIp = oboxIp == null ? null : oboxIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_addr
	 *
	 * @return the value of t_obox.obox_addr
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public String getOboxAddr() {
		return oboxAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_addr
	 *
	 * @param oboxAddr
	 *            the value for t_obox.obox_addr
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxAddr(String oboxAddr) {
		this.oboxAddr = oboxAddr == null ? null : oboxAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_person
	 *
	 * @return the value of t_obox.obox_person
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public Byte getOboxPerson() {
		return oboxPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_person
	 *
	 * @param oboxPerson
	 *            the value for t_obox.obox_person
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxPerson(Byte oboxPerson) {
		this.oboxPerson = oboxPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_activate
	 *
	 * @return the value of t_obox.obox_activate
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public Byte getOboxActivate() {
		return oboxActivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_activate
	 *
	 * @param oboxActivate
	 *            the value for t_obox.obox_activate
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxActivate(Byte oboxActivate) {
		this.oboxActivate = oboxActivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_obox.obox_control
	 *
	 * @return the value of t_obox.obox_control
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public Byte getOboxControl() {
		return oboxControl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_obox.obox_control
	 *
	 * @param oboxControl
	 *            the value for t_obox.obox_control
	 *
	 * @mbg.generated Thu Jun 14 17:09:32 CST 2018
	 */
	public void setOboxControl(Byte oboxControl) {
		this.oboxControl = oboxControl;
	}

	public Integer getId() {
		return id;
	}
	public Integer getOboxId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @param oboxId
	 * @param oboxName
	 * @param oboxSerialId
	 * @param oboxPwd
	 * @param oboxVersion
	 * @param lastOpTime
	 * @param oboxStatus
	 * @param license
	 * @param oboxIp
	 * @param oboxAddr
	 * @param oboxPerson
	 * @param oboxActivate
	 * @param oboxControl
	 */
	public TObox(Integer oboxId, String oboxName, String oboxSerialId, String oboxPwd, String oboxVersion,
			Date lastOpTime, Byte oboxStatus, Integer license, String oboxIp, String oboxAddr, Byte oboxPerson,
			Byte oboxActivate, Byte oboxControl) {
		super();
		this.id = id;
		this.oboxName = oboxName;
		this.oboxSerialId = oboxSerialId;
		this.oboxPwd = oboxPwd;
		this.oboxVersion = oboxVersion;
		this.lastOpTime = lastOpTime;
		this.oboxStatus = oboxStatus;
		this.license = license;
		this.oboxIp = oboxIp;
		this.oboxAddr = oboxAddr;
		this.oboxPerson = oboxPerson;
		this.oboxActivate = oboxActivate;
		this.oboxControl = oboxControl;
	}

	/**  
	 *   
	 */
	public TObox() {
		super();
	}

	@Override
	public String toString() {
		return "TObox [id=" + id + ", oboxName=" + oboxName + ", oboxSerialId=" + oboxSerialId + ", oboxPwd="
				+ oboxPwd + ", oboxVersion=" + oboxVersion + ", lastOpTime=" + lastOpTime + ", oboxStatus=" + oboxStatus
				+ ", license=" + license + ", oboxIp=" + oboxIp + ", oboxAddr=" + oboxAddr + ", oboxPerson="
				+ oboxPerson + ", oboxActivate=" + oboxActivate + ", oboxControl=" + oboxControl + "]";
	}

}