package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TOboxExample implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -4521065733053358075L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public TOboxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOboxNameIsNull() {
            addCriterion("obox_name is null");
            return (Criteria) this;
        }

        public Criteria andOboxNameIsNotNull() {
            addCriterion("obox_name is not null");
            return (Criteria) this;
        }

        public Criteria andOboxNameEqualTo(String value) {
            addCriterion("obox_name =", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameNotEqualTo(String value) {
            addCriterion("obox_name <>", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameGreaterThan(String value) {
            addCriterion("obox_name >", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameGreaterThanOrEqualTo(String value) {
            addCriterion("obox_name >=", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameLessThan(String value) {
            addCriterion("obox_name <", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameLessThanOrEqualTo(String value) {
            addCriterion("obox_name <=", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameLike(String value) {
            addCriterion("obox_name like", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameNotLike(String value) {
            addCriterion("obox_name not like", value, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameIn(List<String> values) {
            addCriterion("obox_name in", values, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameNotIn(List<String> values) {
            addCriterion("obox_name not in", values, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameBetween(String value1, String value2) {
            addCriterion("obox_name between", value1, value2, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxNameNotBetween(String value1, String value2) {
            addCriterion("obox_name not between", value1, value2, "oboxName");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdIsNull() {
            addCriterion("obox_serial_id is null");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdIsNotNull() {
            addCriterion("obox_serial_id is not null");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdEqualTo(String value) {
            addCriterion("obox_serial_id =", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotEqualTo(String value) {
            addCriterion("obox_serial_id <>", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdGreaterThan(String value) {
            addCriterion("obox_serial_id >", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdGreaterThanOrEqualTo(String value) {
            addCriterion("obox_serial_id >=", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdLessThan(String value) {
            addCriterion("obox_serial_id <", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdLessThanOrEqualTo(String value) {
            addCriterion("obox_serial_id <=", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdLike(String value) {
            addCriterion("obox_serial_id like", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotLike(String value) {
            addCriterion("obox_serial_id not like", value, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdIn(List<String> values) {
            addCriterion("obox_serial_id in", values, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotIn(List<String> values) {
            addCriterion("obox_serial_id not in", values, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdBetween(String value1, String value2) {
            addCriterion("obox_serial_id between", value1, value2, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxSerialIdNotBetween(String value1, String value2) {
            addCriterion("obox_serial_id not between", value1, value2, "oboxSerialId");
            return (Criteria) this;
        }

        public Criteria andOboxVersionIsNull() {
            addCriterion("obox_version is null");
            return (Criteria) this;
        }

        public Criteria andOboxVersionIsNotNull() {
            addCriterion("obox_version is not null");
            return (Criteria) this;
        }

        public Criteria andOboxVersionEqualTo(String value) {
            addCriterion("obox_version =", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionNotEqualTo(String value) {
            addCriterion("obox_version <>", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionGreaterThan(String value) {
            addCriterion("obox_version >", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionGreaterThanOrEqualTo(String value) {
            addCriterion("obox_version >=", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionLessThan(String value) {
            addCriterion("obox_version <", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionLessThanOrEqualTo(String value) {
            addCriterion("obox_version <=", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionLike(String value) {
            addCriterion("obox_version like", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionNotLike(String value) {
            addCriterion("obox_version not like", value, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionIn(List<String> values) {
            addCriterion("obox_version in", values, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionNotIn(List<String> values) {
            addCriterion("obox_version not in", values, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionBetween(String value1, String value2) {
            addCriterion("obox_version between", value1, value2, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andOboxVersionNotBetween(String value1, String value2) {
            addCriterion("obox_version not between", value1, value2, "oboxVersion");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNull() {
            addCriterion("last_op_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNotNull() {
            addCriterion("last_op_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeEqualTo(Date value) {
            addCriterion("last_op_time =", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotEqualTo(Date value) {
            addCriterion("last_op_time <>", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThan(Date value) {
            addCriterion("last_op_time >", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_op_time >=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThan(Date value) {
            addCriterion("last_op_time <", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_op_time <=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIn(List<Date> values) {
            addCriterion("last_op_time in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotIn(List<Date> values) {
            addCriterion("last_op_time not in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeBetween(Date value1, Date value2) {
            addCriterion("last_op_time between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_op_time not between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andOboxStatusIsNull() {
            addCriterion("obox_status is null");
            return (Criteria) this;
        }

        public Criteria andOboxStatusIsNotNull() {
            addCriterion("obox_status is not null");
            return (Criteria) this;
        }

        public Criteria andOboxStatusEqualTo(Integer value) {
            addCriterion("obox_status =", value, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusNotEqualTo(Integer value) {
            addCriterion("obox_status <>", value, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusGreaterThan(Integer value) {
            addCriterion("obox_status >", value, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("obox_status >=", value, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusLessThan(Integer value) {
            addCriterion("obox_status <", value, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusLessThanOrEqualTo(Integer value) {
            addCriterion("obox_status <=", value, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusIn(List<Integer> values) {
            addCriterion("obox_status in", values, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusNotIn(List<Integer> values) {
            addCriterion("obox_status not in", values, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusBetween(Integer value1, Integer value2) {
            addCriterion("obox_status between", value1, value2, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("obox_status not between", value1, value2, "oboxStatus");
            return (Criteria) this;
        }

        public Criteria andOboxIpIsNull() {
            addCriterion("obox_ip is null");
            return (Criteria) this;
        }

        public Criteria andOboxIpIsNotNull() {
            addCriterion("obox_ip is not null");
            return (Criteria) this;
        }

        public Criteria andOboxIpEqualTo(String value) {
            addCriterion("obox_ip =", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpNotEqualTo(String value) {
            addCriterion("obox_ip <>", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpGreaterThan(String value) {
            addCriterion("obox_ip >", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpGreaterThanOrEqualTo(String value) {
            addCriterion("obox_ip >=", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpLessThan(String value) {
            addCriterion("obox_ip <", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpLessThanOrEqualTo(String value) {
            addCriterion("obox_ip <=", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpLike(String value) {
            addCriterion("obox_ip like", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpNotLike(String value) {
            addCriterion("obox_ip not like", value, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpIn(List<String> values) {
            addCriterion("obox_ip in", values, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpNotIn(List<String> values) {
            addCriterion("obox_ip not in", values, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpBetween(String value1, String value2) {
            addCriterion("obox_ip between", value1, value2, "oboxIp");
            return (Criteria) this;
        }

        public Criteria andOboxIpNotBetween(String value1, String value2) {
            addCriterion("obox_ip not between", value1, value2, "oboxIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_obox
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 14 16:07:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_obox
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}