package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年12月11日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TRemoteLed implements Serializable{

    /**  
	 *   
	 */
	private static final long serialVersionUID = -6222834715067676697L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_led.id
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_led.name
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_led.serialId
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    private String serialid;
    
    
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_led.last_op_time
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_led.id
     *
     * @return the value of t_remote_led.id
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_led.id
     *
     * @param id the value for t_remote_led.id
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_led.name
     *
     * @return the value of t_remote_led.name
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_led.name
     *
     * @param name the value for t_remote_led.name
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_led.serialId
     *
     * @return the value of t_remote_led.serialId
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_led.serialId
     *
     * @param serialid the value for t_remote_led.serialId
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_led.last_op_time
     *
     * @return the value of t_remote_led.last_op_time
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_led.last_op_time
     *
     * @param lastOpTime the value for t_remote_led.last_op_time
     *
     * @mbg.generated Tue Dec 11 17:44:44 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**  
	 *   
	 */
	public TRemoteLed() {
		super();
	}

	/**  
	 * @param name
	 * @param serialid
	 * @param channel  
	 */
	public TRemoteLed(String name, String serialid, String channel) {
		super();
		this.name = name;
		this.serialid = serialid;
		this.channel = channel;
	}

}
