package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSceneActionExample implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 1901469912945111792L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public TSceneActionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSceneNumberIsNull() {
            addCriterion("scene_number is null");
            return (Criteria) this;
        }

        public Criteria andSceneNumberIsNotNull() {
            addCriterion("scene_number is not null");
            return (Criteria) this;
        }

        public Criteria andSceneNumberEqualTo(Integer value) {
            addCriterion("scene_number =", value, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberNotEqualTo(Integer value) {
            addCriterion("scene_number <>", value, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberGreaterThan(Integer value) {
            addCriterion("scene_number >", value, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("scene_number >=", value, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberLessThan(Integer value) {
            addCriterion("scene_number <", value, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberLessThanOrEqualTo(Integer value) {
            addCriterion("scene_number <=", value, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberIn(List<Integer> values) {
            addCriterion("scene_number in", values, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberNotIn(List<Integer> values) {
            addCriterion("scene_number not in", values, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberBetween(Integer value1, Integer value2) {
            addCriterion("scene_number between", value1, value2, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andSceneNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("scene_number not between", value1, value2, "sceneNumber");
            return (Criteria) this;
        }

        public Criteria andActionidIsNull() {
            addCriterion("actionID is null");
            return (Criteria) this;
        }

        public Criteria andActionidIsNotNull() {
            addCriterion("actionID is not null");
            return (Criteria) this;
        }

        public Criteria andActionidEqualTo(String value) {
            addCriterion("actionID =", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidNotEqualTo(String value) {
            addCriterion("actionID <>", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidGreaterThan(String value) {
            addCriterion("actionID >", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidGreaterThanOrEqualTo(String value) {
            addCriterion("actionID >=", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidLessThan(String value) {
            addCriterion("actionID <", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidLessThanOrEqualTo(String value) {
            addCriterion("actionID <=", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidLike(String value) {
            addCriterion("actionID like", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidNotLike(String value) {
            addCriterion("actionID not like", value, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidIn(List<String> values) {
            addCriterion("actionID in", values, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidNotIn(List<String> values) {
            addCriterion("actionID not in", values, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidBetween(String value1, String value2) {
            addCriterion("actionID between", value1, value2, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionidNotBetween(String value1, String value2) {
            addCriterion("actionID not between", value1, value2, "actionid");
            return (Criteria) this;
        }

        public Criteria andActionIsNull() {
            addCriterion("action is null");
            return (Criteria) this;
        }

        public Criteria andActionIsNotNull() {
            addCriterion("action is not null");
            return (Criteria) this;
        }

        public Criteria andActionEqualTo(String value) {
            addCriterion("action =", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotEqualTo(String value) {
            addCriterion("action <>", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThan(String value) {
            addCriterion("action >", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionGreaterThanOrEqualTo(String value) {
            addCriterion("action >=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThan(String value) {
            addCriterion("action <", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLessThanOrEqualTo(String value) {
            addCriterion("action <=", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionLike(String value) {
            addCriterion("action like", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotLike(String value) {
            addCriterion("action not like", value, "action");
            return (Criteria) this;
        }

        public Criteria andActionIn(List<String> values) {
            addCriterion("action in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotIn(List<String> values) {
            addCriterion("action not in", values, "action");
            return (Criteria) this;
        }

        public Criteria andActionBetween(String value1, String value2) {
            addCriterion("action between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andActionNotBetween(String value1, String value2) {
            addCriterion("action not between", value1, value2, "action");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNull() {
            addCriterion("last_op_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNotNull() {
            addCriterion("last_op_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeEqualTo(Date value) {
            addCriterion("last_op_time =", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotEqualTo(Date value) {
            addCriterion("last_op_time <>", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThan(Date value) {
            addCriterion("last_op_time >", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_op_time >=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThan(Date value) {
            addCriterion("last_op_time <", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_op_time <=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIn(List<Date> values) {
            addCriterion("last_op_time in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotIn(List<Date> values) {
            addCriterion("last_op_time not in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeBetween(Date value1, Date value2) {
            addCriterion("last_op_time between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_op_time not between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andNodeTypeIsNull() {
            addCriterion("node_type is null");
            return (Criteria) this;
        }

        public Criteria andNodeTypeIsNotNull() {
            addCriterion("node_type is not null");
            return (Criteria) this;
        }

        public Criteria andNodeTypeEqualTo(String value) {
            addCriterion("node_type =", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotEqualTo(String value) {
            addCriterion("node_type <>", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeGreaterThan(String value) {
            addCriterion("node_type >", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("node_type >=", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeLessThan(String value) {
            addCriterion("node_type <", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeLessThanOrEqualTo(String value) {
            addCriterion("node_type <=", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeLike(String value) {
            addCriterion("node_type like", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotLike(String value) {
            addCriterion("node_type not like", value, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeIn(List<String> values) {
            addCriterion("node_type in", values, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotIn(List<String> values) {
            addCriterion("node_type not in", values, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeBetween(String value1, String value2) {
            addCriterion("node_type between", value1, value2, "nodeType");
            return (Criteria) this;
        }

        public Criteria andNodeTypeNotBetween(String value1, String value2) {
            addCriterion("node_type not between", value1, value2, "nodeType");
            return (Criteria) this;
        }

        public Criteria andPresetIsNull() {
            addCriterion("preSet is null");
            return (Criteria) this;
        }

        public Criteria andPresetIsNotNull() {
            addCriterion("preSet is not null");
            return (Criteria) this;
        }

        public Criteria andPresetEqualTo(Integer value) {
            addCriterion("preSet =", value, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetNotEqualTo(Integer value) {
            addCriterion("preSet <>", value, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetGreaterThan(Integer value) {
            addCriterion("preSet >", value, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetGreaterThanOrEqualTo(Integer value) {
            addCriterion("preSet >=", value, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetLessThan(Integer value) {
            addCriterion("preSet <", value, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetLessThanOrEqualTo(Integer value) {
            addCriterion("preSet <=", value, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetIn(List<Integer> values) {
            addCriterion("preSet in", values, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetNotIn(List<Integer> values) {
            addCriterion("preSet not in", values, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetBetween(Integer value1, Integer value2) {
            addCriterion("preSet between", value1, value2, "preset");
            return (Criteria) this;
        }

        public Criteria andPresetNotBetween(Integer value1, Integer value2) {
            addCriterion("preSet not between", value1, value2, "preset");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_scene_action
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 02 10:21:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_scene_action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}