package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TSceneCondition implements Serializable {
	/**  
	 *   
	 */
	private static final long serialVersionUID = -6940520018475383170L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene_condition.id
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene_condition.scene_number
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	private Integer sceneNumber;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene_condition.serialId
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	private String serialid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene_condition.last_op_time
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	private Date lastOpTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene_condition.cond
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	private String cond;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_scene_condition.condition_group
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	private Integer conditionGroup;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_scene_condition.id
	 *
	 * @return the value of t_scene_condition.id
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_scene_condition.id
	 *
	 * @param id
	 *            the value for t_scene_condition.id
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_scene_condition.scene_number
	 *
	 * @return the value of t_scene_condition.scene_number
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public Integer getSceneNumber() {
		return sceneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_scene_condition.scene_number
	 *
	 * @param sceneNumber
	 *            the value for t_scene_condition.scene_number
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public void setSceneNumber(Integer sceneNumber) {
		this.sceneNumber = sceneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_scene_condition.serialId
	 *
	 * @return the value of t_scene_condition.serialId
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public String getSerialid() {
		return serialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_scene_condition.serialId
	 *
	 * @param serialid
	 *            the value for t_scene_condition.serialId
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public void setSerialid(String serialid) {
		this.serialid = serialid == null ? null : serialid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_scene_condition.last_op_time
	 *
	 * @return the value of t_scene_condition.last_op_time
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public Date getLastOpTime() {
		return lastOpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_scene_condition.last_op_time
	 *
	 * @param lastOpTime
	 *            the value for t_scene_condition.last_op_time
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public void setLastOpTime(Date lastOpTime) {
		this.lastOpTime = lastOpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_scene_condition.cond
	 *
	 * @return the value of t_scene_condition.cond
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public String getCond() {
		return cond;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_scene_condition.cond
	 *
	 * @param cond
	 *            the value for t_scene_condition.cond
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public void setCond(String cond) {
		this.cond = cond == null ? null : cond.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_scene_condition.condition_group
	 *
	 * @return the value of t_scene_condition.condition_group
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public Integer getConditionGroup() {
		return conditionGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_scene_condition.condition_group
	 *
	 * @param conditionGroup
	 *            the value for t_scene_condition.condition_group
	 *
	 * @mbg.generated Mon Mar 19 16:11:25 CST 2018
	 */
	public void setConditionGroup(Integer conditionGroup) {
		this.conditionGroup = conditionGroup;
	}

	/**
	 * @param id
	 */
	public TSceneCondition(Integer id) {
		super();
		this.id = id;
	}

	public TSceneCondition() {}

}