package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TSceneAction implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -5433590118091553382L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.scene_number
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer sceneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.actionID
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private String actionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.node_type
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private String nodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scene_action.preSet
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer preset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.id
     *
     * @return the value of t_scene_action.id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.id
     *
     * @param id the value for t_scene_action.id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.scene_number
     *
     * @return the value of t_scene_action.scene_number
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getSceneNumber() {
        return sceneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.scene_number
     *
     * @param sceneNumber the value for t_scene_action.scene_number
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setSceneNumber(Integer sceneNumber) {
        this.sceneNumber = sceneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.actionID
     *
     * @return the value of t_scene_action.actionID
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public String getActionid() {
        return actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.actionID
     *
     * @param actionid the value for t_scene_action.actionID
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setActionid(String actionid) {
        this.actionid = actionid == null ? null : actionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.action
     *
     * @return the value of t_scene_action.action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.action
     *
     * @param action the value for t_scene_action.action
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.last_op_time
     *
     * @return the value of t_scene_action.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.last_op_time
     *
     * @param lastOpTime the value for t_scene_action.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.node_type
     *
     * @return the value of t_scene_action.node_type
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.node_type
     *
     * @param nodeType the value for t_scene_action.node_type
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scene_action.preSet
     *
     * @return the value of t_scene_action.preSet
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getPreset() {
        return preset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scene_action.preSet
     *
     * @param preset the value for t_scene_action.preSet
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setPreset(Integer preset) {
        this.preset = preset;
    }

	/**  
	 * @param id  
	 */
	public TSceneAction(Integer id) {
		super();
		this.id = id;
	}

    public TSceneAction() {

    }
    
}