package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TSystem implements Serializable{
 
 
	/**  
	 *   
	 */
	private static final long serialVersionUID = -4497108618204665559L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.last_op_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.child_type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer childType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.relevancy_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    private Integer relevancyId;

    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.id
     *
     * @return the value of t_system.id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.id
     *
     * @param id the value for t_system.id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.last_op_time
     *
     * @return the value of t_system.last_op_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.last_op_time
     *
     * @param lastOpTime the value for t_system.last_op_time
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.type
     *
     * @return the value of t_system.type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.type
     *
     * @param type the value for t_system.type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.child_type
     *
     * @return the value of t_system.child_type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getChildType() {
        return childType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.child_type
     *
     * @param childType the value for t_system.child_type
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setChildType(Integer childType) {
        this.childType = childType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.relevancy_id
     *
     * @return the value of t_system.relevancy_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public Integer getRelevancyId() {
        return relevancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.relevancy_id
     *
     * @param relevancyId the value for t_system.relevancy_id
     *
     * @mbg.generated Thu Oct 18 15:19:53 CST 2018
     */
    public void setRelevancyId(Integer relevancyId) {
        this.relevancyId = relevancyId;
    }
    public TSystem() {
		super();
	}

	public TSystem(Integer type, Integer childType, Integer relevancyId) {
		super();
		this.type = type;
		this.childType = childType;
		this.relevancyId = relevancyId;
 	}
}