package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TUserObox implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -6756476007380326518L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_obox.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_obox.obox_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private String oboxSerialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_obox.user_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_obox.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_obox.privilege
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_obox.id
     *
     * @return the value of t_user_obox.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_obox.id
     *
     * @param id the value for t_user_obox.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_obox.obox_serial_id
     *
     * @return the value of t_user_obox.obox_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOboxSerialId() {
        return oboxSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_obox.obox_serial_id
     *
     * @param oboxSerialId the value for t_user_obox.obox_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOboxSerialId(String oboxSerialId) {
        this.oboxSerialId = oboxSerialId == null ? null : oboxSerialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_obox.user_id
     *
     * @return the value of t_user_obox.user_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_obox.user_id
     *
     * @param userId the value for t_user_obox.user_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_obox.last_op_time
     *
     * @return the value of t_user_obox.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_obox.last_op_time
     *
     * @param lastOpTime the value for t_user_obox.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_obox.privilege
     *
     * @return the value of t_user_obox.privilege
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_obox.privilege
     *
     * @param privilege the value for t_user_obox.privilege
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setPrivilege(Integer privilege) {
        this.privilege = privilege;
    }
}