package com.bright.apollo.common.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年11月23日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TUserLocation {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_user_location.user_id
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   @JsonProperty(value = "user_id")
   private Integer userId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_user_location.location_id
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   @JsonProperty(value = "location_id")
   private Integer locationId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_user_location.last_op_time
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   @JsonProperty(value = "last_op_time")
   private Date lastOpTime;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_user_location.user_id
    *
    * @return the value of t_user_location.user_id
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   public Integer getUserId() {
       return userId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_user_location.user_id
    *
    * @param userId the value for t_user_location.user_id
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   public void setUserId(Integer userId) {
       this.userId = userId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_user_location.location_id
    *
    * @return the value of t_user_location.location_id
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   public Integer getLocationId() {
       return locationId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_user_location.location_id
    *
    * @param locationId the value for t_user_location.location_id
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   public void setLocationId(Integer locationId) {
       this.locationId = locationId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_user_location.last_op_time
    *
    * @return the value of t_user_location.last_op_time
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   public Date getLastOpTime() {
       return lastOpTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_user_location.last_op_time
    *
    * @param lastOpTime the value for t_user_location.last_op_time
    *
    * @mbg.generated Fri Nov 23 16:33:02 CST 2018
    */
   public void setLastOpTime(Date lastOpTime) {
       this.lastOpTime = lastOpTime;
   }
}
