package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TUSerGroup implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 2012495522402866373L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_group.user_id
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_group.group_id
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_group.last_op_time
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_group.user_id
     *
     * @return the value of t_user_group.user_id
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_group.user_id
     *
     * @param userId the value for t_user_group.user_id
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_group.group_id
     *
     * @return the value of t_user_group.group_id
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_group.group_id
     *
     * @param groupId the value for t_user_group.group_id
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_group.last_op_time
     *
     * @return the value of t_user_group.last_op_time
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_group.last_op_time
     *
     * @param lastOpTime the value for t_user_group.last_op_time
     *
     * @mbg.generated Tue Oct 30 11:00:18 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

	@Override
	public String toString() {
		return "TUSerGroup [userId=" + userId + ", groupId=" + groupId + ", lastOpTime=" + lastOpTime + "]";
	}
    
}