package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TUserDevice implements Serializable{
    /**
	 *   
	 */
	private static final long serialVersionUID = 741059402616829047L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_device.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_device.device_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private String deviceSerialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_device.user_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_device.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_device.privilege
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    private Integer privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_device.id
     *
     * @return the value of t_user_device.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_device.id
     *
     * @param id the value for t_user_device.id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_device.device_serial_id
     *
     * @return the value of t_user_device.device_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getDeviceSerialId() {
        return deviceSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_device.device_serial_id
     *
     * @param deviceSerialId the value for t_user_device.device_serial_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setDeviceSerialId(String deviceSerialId) {
        this.deviceSerialId = deviceSerialId == null ? null : deviceSerialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_device.user_id
     *
     * @return the value of t_user_device.user_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_device.user_id
     *
     * @param userId the value for t_user_device.user_id
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_device.last_op_time
     *
     * @return the value of t_user_device.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_device.last_op_time
     *
     * @param lastOpTime the value for t_user_device.last_op_time
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_device.privilege
     *
     * @return the value of t_user_device.privilege
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Integer getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_device.privilege
     *
     * @param privilege the value for t_user_device.privilege
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setPrivilege(Integer privilege) {
        this.privilege = privilege;
    }
}