package com.bright.apollo.common.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class TUserDeviceExample implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 3692982676857957330L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public TUserDeviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdIsNull() {
            addCriterion("device_serial_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdIsNotNull() {
            addCriterion("device_serial_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdEqualTo(String value) {
            addCriterion("device_serial_id =", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotEqualTo(String value) {
            addCriterion("device_serial_id <>", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdGreaterThan(String value) {
            addCriterion("device_serial_id >", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdGreaterThanOrEqualTo(String value) {
            addCriterion("device_serial_id >=", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdLessThan(String value) {
            addCriterion("device_serial_id <", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdLessThanOrEqualTo(String value) {
            addCriterion("device_serial_id <=", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdLike(String value) {
            addCriterion("device_serial_id like", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotLike(String value) {
            addCriterion("device_serial_id not like", value, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdIn(List<String> values) {
            addCriterion("device_serial_id in", values, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotIn(List<String> values) {
            addCriterion("device_serial_id not in", values, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdBetween(String value1, String value2) {
            addCriterion("device_serial_id between", value1, value2, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andDeviceSerialIdNotBetween(String value1, String value2) {
            addCriterion("device_serial_id not between", value1, value2, "deviceSerialId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNull() {
            addCriterion("last_op_time is null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIsNotNull() {
            addCriterion("last_op_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeEqualTo(Date value) {
            addCriterion("last_op_time =", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotEqualTo(Date value) {
            addCriterion("last_op_time <>", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThan(Date value) {
            addCriterion("last_op_time >", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_op_time >=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThan(Date value) {
            addCriterion("last_op_time <", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_op_time <=", value, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeIn(List<Date> values) {
            addCriterion("last_op_time in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotIn(List<Date> values) {
            addCriterion("last_op_time not in", values, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeBetween(Date value1, Date value2) {
            addCriterion("last_op_time between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andLastOpTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_op_time not between", value1, value2, "lastOpTime");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIsNull() {
            addCriterion("privilege is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIsNotNull() {
            addCriterion("privilege is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeEqualTo(Integer value) {
            addCriterion("privilege =", value, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNotEqualTo(Integer value) {
            addCriterion("privilege <>", value, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeGreaterThan(Integer value) {
            addCriterion("privilege >", value, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeGreaterThanOrEqualTo(Integer value) {
            addCriterion("privilege >=", value, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeLessThan(Integer value) {
            addCriterion("privilege <", value, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeLessThanOrEqualTo(Integer value) {
            addCriterion("privilege <=", value, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIn(List<Integer> values) {
            addCriterion("privilege in", values, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNotIn(List<Integer> values) {
            addCriterion("privilege not in", values, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeBetween(Integer value1, Integer value2) {
            addCriterion("privilege between", value1, value2, "privilege");
            return (Criteria) this;
        }

        public Criteria andPrivilegeNotBetween(Integer value1, Integer value2) {
            addCriterion("privilege not between", value1, value2, "privilege");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_device
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 14 16:07:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_device
     *
     * @mbg.generated Wed Mar 14 16:07:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}