package com.bright.apollo.common.entity;  
  
import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年10月17日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TUserAliDevice implements Serializable{

    /**  
	 *   
	 */
	private static final long serialVersionUID = -7514039764411456756L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ali_device.id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ali_device.user_id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ali_device.device_serial_id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    private String deviceSerialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ali_device.last_op_time
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ali_device.id
     *
     * @return the value of t_user_ali_device.id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ali_device.id
     *
     * @param id the value for t_user_ali_device.id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ali_device.user_id
     *
     * @return the value of t_user_ali_device.user_id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ali_device.user_id
     *
     * @param userId the value for t_user_ali_device.user_id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ali_device.device_serial_id
     *
     * @return the value of t_user_ali_device.device_serial_id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public String getDeviceSerialId() {
        return deviceSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ali_device.device_serial_id
     *
     * @param deviceSerialId the value for t_user_ali_device.device_serial_id
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public void setDeviceSerialId(String deviceSerialId) {
        this.deviceSerialId = deviceSerialId == null ? null : deviceSerialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ali_device.last_op_time
     *
     * @return the value of t_user_ali_device.last_op_time
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ali_device.last_op_time
     *
     * @param lastOpTime the value for t_user_ali_device.last_op_time
     *
     * @mbg.generated Wed Oct 17 10:46:50 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

}
