package com.bright.apollo.common.entity;

import java.io.Serializable;

public class TUserSceneKey implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = -7076815541301775890L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_scene.user_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_scene.scene_number
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer sceneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene.user_id
     *
     * @return the value of t_user_scene.user_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene.user_id
     *
     * @param userId the value for t_user_scene.user_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene.scene_number
     *
     * @return the value of t_user_scene.scene_number
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getSceneNumber() {
        return sceneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene.scene_number
     *
     * @param sceneNumber the value for t_user_scene.scene_number
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setSceneNumber(Integer sceneNumber) {
        this.sceneNumber = sceneNumber;
    }
}