package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年12月19日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(value = { "lastOpTime","id" })
public class TUserSceneTemplate implements Serializable{

    /**  
	 *   
	 */
	private static final long serialVersionUID = -3982836225529602838L;
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_scene_template.id
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
	@JsonProperty(value="id")
    private Integer id;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_user_scene_template.scene_model
    *
    * @mbg.generated Wed Dec 19 11:59:13 CST 2018
    */
	@JsonProperty(value="sceneModel")
   private String sceneModel;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_scene_template.modelName
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
	@JsonProperty(value="modelName")
    private String modelname;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_user_scene_template.device_model
    *
    * @mbg.generated Wed Dec 19 11:59:13 CST 2018
    */
	@JsonProperty(value="deviceModel")
   private String deviceModel;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_scene_template.user_id
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
	@JsonProperty(value="userId")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_scene_template.last_op_time
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
	@JsonProperty(value="lastOpTime")
    private Date lastOpTime;

    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene_template.id
     *
     * @return the value of t_user_scene_template.id
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene_template.id
     *
     * @param id the value for t_user_scene_template.id
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene_template.modelName
     *
     * @return the value of t_user_scene_template.modelName
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene_template.modelName
     *
     * @param modelname the value for t_user_scene_template.modelName
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public void setModelname(String modelname) {
        this.modelname = modelname == null ? null : modelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene_template.user_id
     *
     * @return the value of t_user_scene_template.user_id
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene_template.user_id
     *
     * @param userId the value for t_user_scene_template.user_id
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene_template.last_op_time
     *
     * @return the value of t_user_scene_template.last_op_time
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene_template.last_op_time
     *
     * @param lastOpTime the value for t_user_scene_template.last_op_time
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene_template.scene_model
     *
     * @return the value of t_user_scene_template.scene_model
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public String getSceneModel() {
        return sceneModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene_template.scene_model
     *
     * @param sceneModel the value for t_user_scene_template.scene_model
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public void setSceneModel(String sceneModel) {
        this.sceneModel = sceneModel == null ? null : sceneModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_scene_template.device_model
     *
     * @return the value of t_user_scene_template.device_model
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_scene_template.device_model
     *
     * @param deviceModel the value for t_user_scene_template.device_model
     *
     * @mbg.generated Wed Dec 19 11:59:13 CST 2018
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }

	/**  
	 * @param sceneModel
	 * @param modelname
	 * @param deviceModel
	 * @param userId  
	 */
	public TUserSceneTemplate(String sceneModel, String modelname, String deviceModel, Integer userId) {
		super();
		this.sceneModel = sceneModel;
		this.modelname = modelname;
		this.deviceModel = deviceModel;
		this.userId = userId;
	}

	/**  
	 *   
	 */
	public TUserSceneTemplate() {
		super();
	}
    
    
}
