package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;

public class TUserPhone implements Serializable{
    /**  
	 *   
	 */
	private static final long serialVersionUID = 4701931382333078664L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone.user_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone.phone
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_phone.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    private Date lastOpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone.user_id
     *
     * @return the value of t_user_phone.user_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone.user_id
     *
     * @param userId the value for t_user_phone.user_id
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone.phone
     *
     * @return the value of t_user_phone.phone
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone.phone
     *
     * @param phone the value for t_user_phone.phone
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_phone.last_op_time
     *
     * @return the value of t_user_phone.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_phone.last_op_time
     *
     * @param lastOpTime the value for t_user_phone.last_op_time
     *
     * @mbg.generated Fri Mar 02 10:21:07 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }
}