package com.bright.apollo.common.entity;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonInclude;

/**  
 *@Title:  
 *@Description:  
 *@Author:JettyLiu
 *@Since:2018年6月28日  
 *@Version:1.1.0  
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TYSCamera implements Serializable {

	/**  
	 *   
	 */
	private static final long serialVersionUID = -7064611450111117285L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.id
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.channelName
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private String channelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.deviceSerial
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private String deviceserial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.deviceType
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private String devicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.status
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.isShared
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Byte isshared;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.deviceVersion
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private String deviceversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.last_op_time
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Date lastOpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.license
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Integer license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.channelNo
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private String channelno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.picUrl
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.isEncrypt
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Byte isencrypt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ys_camera.videoLevel
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    private Byte videolevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.id
     *
     * @return the value of t_ys_camera.id
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.id
     *
     * @param id the value for t_ys_camera.id
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.channelName
     *
     * @return the value of t_ys_camera.channelName
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public String getChannelname() {
        return channelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.channelName
     *
     * @param channelname the value for t_ys_camera.channelName
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setChannelname(String channelname) {
        this.channelname = channelname == null ? null : channelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.deviceSerial
     *
     * @return the value of t_ys_camera.deviceSerial
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public String getDeviceserial() {
        return deviceserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.deviceSerial
     *
     * @param deviceserial the value for t_ys_camera.deviceSerial
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setDeviceserial(String deviceserial) {
        this.deviceserial = deviceserial == null ? null : deviceserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.deviceType
     *
     * @return the value of t_ys_camera.deviceType
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public String getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.deviceType
     *
     * @param devicetype the value for t_ys_camera.deviceType
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype == null ? null : devicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.status
     *
     * @return the value of t_ys_camera.status
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.status
     *
     * @param status the value for t_ys_camera.status
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.isShared
     *
     * @return the value of t_ys_camera.isShared
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Byte getIsshared() {
        return isshared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.isShared
     *
     * @param isshared the value for t_ys_camera.isShared
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setIsshared(Byte isshared) {
        this.isshared = isshared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.deviceVersion
     *
     * @return the value of t_ys_camera.deviceVersion
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public String getDeviceversion() {
        return deviceversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.deviceVersion
     *
     * @param deviceversion the value for t_ys_camera.deviceVersion
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setDeviceversion(String deviceversion) {
        this.deviceversion = deviceversion == null ? null : deviceversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.last_op_time
     *
     * @return the value of t_ys_camera.last_op_time
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Date getLastOpTime() {
        return lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.last_op_time
     *
     * @param lastOpTime the value for t_ys_camera.last_op_time
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setLastOpTime(Date lastOpTime) {
        this.lastOpTime = lastOpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.license
     *
     * @return the value of t_ys_camera.license
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Integer getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.license
     *
     * @param license the value for t_ys_camera.license
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setLicense(Integer license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.channelNo
     *
     * @return the value of t_ys_camera.channelNo
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public String getChannelno() {
        return channelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.channelNo
     *
     * @param channelno the value for t_ys_camera.channelNo
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setChannelno(String channelno) {
        this.channelno = channelno == null ? null : channelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.picUrl
     *
     * @return the value of t_ys_camera.picUrl
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.picUrl
     *
     * @param picurl the value for t_ys_camera.picUrl
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.isEncrypt
     *
     * @return the value of t_ys_camera.isEncrypt
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Byte getIsencrypt() {
        return isencrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.isEncrypt
     *
     * @param isencrypt the value for t_ys_camera.isEncrypt
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setIsencrypt(Byte isencrypt) {
        this.isencrypt = isencrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ys_camera.videoLevel
     *
     * @return the value of t_ys_camera.videoLevel
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public Byte getVideolevel() {
        return videolevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ys_camera.videoLevel
     *
     * @param videolevel the value for t_ys_camera.videoLevel
     *
     * @mbg.generated Thu Jun 28 14:52:37 CST 2018
     */
    public void setVideolevel(Byte videolevel) {
        this.videolevel = videolevel;
    }

}
