server:
  port: 8800
<<<<<<< HEAD
eureka:
  client:
    service-url:
      defaultZone: http://root:booszy@47.99.107.215:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
=======
>>>>>>> obTest
spring:
  profiles:
    active: dev
  application:
<<<<<<< HEAD
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onbright-canton/onbrightConfig/
          searchPaths: '{application}'
  rabbitmq:
    host: 47.99.107.215
    port: 5672
    username: liujj
    password: liujj123456
#test rabbitmq
#  rabbitmq:
#    host: 192.168.200.212
#    port: 5672
#    username: admin
#    password: 123456
security:
  basic:
    enabled: true
  user:
    name: root
    password: booszy
logging:
  config: classpath:logback-config.xml
=======
    name: springcloud-config-server
>>>>>>> obTest
