server:
  port: 8800
eureka:
  client:
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onbright-canton/onbrightConfig/
          searchPaths: '{application}'
  rabbitmq:
    host: 192.168.200.212
    port: 5672
    username: admin
    password: 123456
security:
  basic:
    enabled: false
  user:
    name: root
    password: booszy
logging:
  config: classpath:logback-config.xml