server:
  port: 8815
  tomcat:
    protocol-header: x-forwarded-proto
  use-forward-headers: true
spring:
  application:
    name: springcloud-oauth2
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:booszy@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-oauth2	

management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
    enabled: true
redis:
    database: 0
    host: 120.27.212.190
    port: 6379
    timeout: 3000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0